### ISSUE TITLE
How do I set this up?

### ISSUE THREAD

**Issue by Sushi8756** [warrenm/AugmentedMario#1]
As the title says, how do I set this up so I can use it?
I'm kinda a newbie so I don't know much about this stuff, and I would like to use it. :)

**Comment by warrenm** [comment]
Sorry, this was just a quick experiment, so I'm not offering support on it.

To build and run the app, you'll need a Super Mario 64 (U.S. edition) ROM, which I can't provide for legal reasons. Other than that, you'll need a recent-ish Mac running Xcode 13 and an iOS device running iOS 13.0 or newer.
